# Generated by Django 5.0.1 on 2024-01-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField(default='')),
                ('stu_name', models.CharField(default='', max_length=20)),
                ('stu_year', models.IntegerField(default='')),
                ('stu_sport', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
